# Workflow to build and test wheels
name: Run tests

on: push

jobs:

  # Build the wheels for Linux, Windows and macOS for Python 3.6 and newer
  test_skimage:
    name: Run tests cp${{ matrix.python-version }}-${{ matrix.platform_id }}
    runs-on: ${{ matrix.os }}

    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8]
        bitness: [64]
        include:
          # Run 32 and 64 bit version in parallel for Linux and Windows
          - os: windows-latest
            bitness: 64
            platform_id: win_amd64
            #- os: windows-latest
            #bitness: 32
            #platform_id: win32
          - os: ubuntu-latest
            bitness: 64
            platform_id: manylinux_x86_64
            #- os: ubuntu-latest
            #bitness: 32
            #platform_id: manylinux_i686
          - os: macos-latest
            bitness: 64
            platform_id: macosx_x86_64

    steps:
      - name: Checkout scikit-image
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version}}

      - name: OSX configuration
        if: ${{ matrix.os }} == "macos-latest"
        run: |
            # OpenMP is not present on macOS by default
            brew install libomp
            export CC=/usr/bin/clang
            export CXX=/usr/bin/clang++
            export CPPFLAGS="$CPPFLAGS -Xpreprocessor -fopenmp"
            export CFLAGS="$CFLAGS -I/usr/local/opt/libomp/include"
            export CXXFLAGS="$CXXFLAGS -I/usr/local/opt/libomp/include"
            export LDFLAGS="$LDFLAGS -Wl,-rpath,/usr/local/opt/libomp/lib -L/usr/local/opt/libomp/lib -lomp"

      - name: print options
        if: ${{ matrix.os }} == "macos-latest" || ${{ matrix.os }} == "ubuntu-latest"
        run: set -ex
    
      - name: Build package
        run: |
            python -m venv ~/venv;
            source ~/venv/bin/activate;
            source tools/github/before_install.sh
            python setup.py sdist
            pip install -vv --no-build-isolation -e .;

      - name: Run tests
        run: |
            source ~/venv/bin/activate;
            pip install $PIP_FLAGS -r requirements/test.txt
            export MPL_DIR=`python -c 'import matplotlib; print(matplotlib.get_configdir())'`
            mkdir -p ${MPL_DIR}
            touch ${MPL_DIR}/matplotlibrc
            pip install -r ./requirements/optional.txt
            pip install -r ./requirements/extras.txt
            source tools/github/script.sh



