# Workflow to build and test wheels
name: Run tests

on: [push, pull request]

jobs:

  # Build the wheels for Linux, Windows and macOS for Python 3.6 and newer
  test_skimage:
    name: Run tests cp${{ matrix.python }}-${{ matrix.platform_id }}
    runs-on: ${{ matrix.os }}

    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python: [37, 38]
        bitness: [32, 64]
        include:
          # Run 32 and 64 bit version in parallel for Linux and Windows
          - os: windows-latest
            bitness: 64
            platform_id: win_amd64
            #- os: windows-latest
            #bitness: 32
            #platform_id: win32
          - os: ubuntu-latest
            bitness: 64
            platform_id: manylinux_x86_64
            #- os: ubuntu-latest
            #bitness: 32
            #platform_id: manylinux_i686
          - os: macos-latest
            bitness: 64
            platform_id: macosx_x86_64
        exclude:
          - os: macos-latest
            bitness: 32

    steps:
      - name: Checkout scikit-image
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Build package
        run: |
            set -ex
            if [[ ${{ matrix.platform_id }} == "macos-latest" ]]; then
                source tools/travis/osx_install.sh;
            else
                virtualenv -p python ~/venv;
                source ~/venv/bin/activate;
            fi
            source tools/github/before_install.sh
            python setup.py sdist
            pip install -vv --no-build-isolation -e .;

      - name: Run tests
        run: |
            pip install $PIP_FLAGS -r requirements/test.txt
            export MPL_DIR=`python -c 'import matplotlib; print(matplotlib.get_configdir())'`
            mkdir -p ${MPL_DIR}
            touch ${MPL_DIR}/matplotlibrc
            pip install -r ./requirements/optional.txt
            pip install -r ./requirements/extras.txt



